version: 2
updates:
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    groups:
      container-build-images:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    groups:
      compose-images:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
